# Generated by Django 5.1.1 on 2025-11-29 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='autoridades/')),
                ('descripcion_opcional', models.TextField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Autoridades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='contenidos/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='contenidos/pdf/')),
                ('archivo_video', models.FileField(blank=True, null=True, upload_to='contenidos/videos/')),
                ('link_video', models.URLField(blank=True, help_text='Enlace de YouTube o similar', null=True)),
                ('estado_publicacion', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público')], default='privado', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Contenidos',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=50)),
                ('paralelo', models.CharField(blank=True, max_length=10, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='GaleriaImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(default='general', help_text='Categoría para filtrar imágenes', max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen Galería',
                'verbose_name_plural': 'Imágenes Galería',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen_principal', models.ImageField(upload_to='contenidos/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Historias',
            },
        ),
        migrations.CreateModel(
            name='InformacionColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('telefono_1', models.CharField(max_length=20)),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('latitud', models.FloatField(help_text='Para Google Maps')),
                ('longitud', models.FloatField(help_text='Para Google Maps')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colegio/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='colegio/')),
            ],
            options={
                'verbose_name': 'Información del Colegio',
                'verbose_name_plural': 'Información del Colegio',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('curso', models.CharField(help_text='Ej: 1° Secundaria', max_length=50)),
                ('paralelo', models.CharField(help_text='Ej: A, B, C', max_length=10)),
                ('imagen_portada', models.ImageField(upload_to='materias/')),
                ('estado_publicacion', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada')], default='borrador', max_length=20)),
                ('color_portada', models.CharField(default='#3498db', help_text='Color hexadecimal para la tarjeta', max_length=7)),
                ('icono', models.CharField(blank=True, help_text='Ej: fa-calculator', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('imagen_opcional', models.ImageField(blank=True, null=True, upload_to='contenidos/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Misiones',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('destacada', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='profesores/')),
                ('descripcion_corta', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profesor Público',
                'verbose_name_plural': 'Profesores Públicos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('imagen_opcional', models.ImageField(blank=True, null=True, upload_to='contenidos/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Visiones',
            },
        ),
        migrations.CreateModel(
            name='ImagenContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='contenidos/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.contenido')),
            ],
            options={
                'verbose_name': 'Imagen Contenido',
                'verbose_name_plural': 'Imágenes Contenido',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.materia'),
        ),
        migrations.CreateModel(
            name='ProfesorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesores/')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Profesor',
                'verbose_name_plural': 'Perfiles Profesores',
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.profesorprofile'),
        ),
    ]
