# Generated by Django 5.1.1 on 2025-11-29 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='contenidos/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='contenidos/pdf/')),
                ('archivo_video', models.FileField(blank=True, null=True, upload_to='contenidos/videos/')),
                ('link_video', models.URLField(blank=True, help_text='Enlace de YouTube o similar', null=True)),
                ('estado_publicacion', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público')], default='privado', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Contenidos',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('curso', models.CharField(help_text='Ej: 1° Secundaria', max_length=50)),
                ('paralelo', models.CharField(help_text='Ej: A, B, C', max_length=10)),
                ('imagen_portada', models.ImageField(upload_to='materias/')),
                ('estado_publicacion', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada')], default='borrador', max_length=20)),
                ('color_portada', models.CharField(default='#3498db', help_text='Color hexadecimal para la tarjeta', max_length=7)),
                ('icono', models.CharField(blank=True, help_text='Ej: fa-calculator', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='contenidos/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.contenido')),
            ],
            options={
                'verbose_name': 'Imagen Contenido',
                'verbose_name_plural': 'Imágenes Contenido',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.materia'),
        ),
        migrations.CreateModel(
            name='ProfesorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesores/')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Profesor',
                'verbose_name_plural': 'Perfiles Profesores',
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.profesorprofile'),
        ),
    ]
