# Generated by Django 5.1.1 on 2025-11-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contenido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='materias/fotos/'),
        ),
    ]
